name: Check sever side script
on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - master
      - develop
      - 'feature/**'
jobs:
  build:
  app-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: checkout 
        uses: actions/checkout@v2
      # dockerコンテナを起動
      - name: docker-compose up
        run: docker-compose up -d
      - name: Copy Environment File
        run: docker-compose exec -T app cp .env.example .env
      - name: Install Dependencies
        run: docker-compose exec -T app composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: docker-compose exec -T app php artisan key:generate
      ## dbの起動を待機
      - name: Wait DB
        run : docker-compose exec -T db bash -c "mysqladmin --wait --count 60 ping -proot || exit 1"
      ## マイグレーション
      - name: migration
        run: docker-compose exec -T app php artisan migrate --seed
      ## test実行
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: docker-compose exec -T app ./vendor/bin/phpunit